/**
 * AUTH ACTIONS
 */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

/**
 * DASHBOARD ACTIONS
 */
export const GET_ALL_APPOINTMENT = 'GET_ALL_APPOINTMENT';
export const GET_ALL_APPOINTMENT_SUCCESS = 'GET_ALL_APPOINTMENT_SUCCESS';
export const GET_ALL_APPOINTMENT_FAILED = 'GET_ALL_APPOINTMENT_FAILED';
export const GET_ALL_NOTIFICATION = 'GET_ALL_NOTIFICATION';
export const GET_ALL_NOTIFICATION_SUCCESS = 'GET_ALL_NOTIFICATION_SUCCESS';
export const GET_ALL_NOTIFICATION_FAILED = 'GET_ALL_NOTIFICATION_FAILED';

/**
 * MY PATIENT ACTIONS
 */
export const GET_ALL_MY_PATIENT = 'GET_ALL_MY_PATIENT';
export const GET_ALL_MY_PATIENT_SUCCESS = 'GET_ALL_MY_PATIENT_SUCCESS';
export const GET_ALL_MY_PATIENT_FAILED = 'GET_ALL_MY_PATIENT_FAILED';

/**
 * RESET ACTIONS
 */
export const RESET_PROPS_STATE = 'RESET_PROPS_STATE';
export const RESET_ERROR_STATE = 'RESET_ERROR_STATE';
